version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      # Initialization script, might not be required
      # - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - django-network

  django:
    build: ./skills_DS
    container_name: django
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000 
    volumes:
      - ./skills_DS:/app/django
    networks:
      - django-network
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

networks:
  django-network:
    driver: bridge
