# Generated by Django 4.0.1 on 2022-01-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='industry',
        ),
    ]
