# Generated by Django 4.0.1 on 2022-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_jobtitle_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=49.28, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=116.23, max_digits=13),
            preserve_default=False,
        ),
    ]
