# Generated by Django 4.0.1 on 2022-02-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobposting_scraped_skill_invalidskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidskill',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobtitle'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
    ]
