# Generated by Django 4.0.1 on 2022-02-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invalidskill_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_title', to='api.jobtitle'),
        ),
    ]
