# Generated by Django 4.0.1 on 2022-04-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_jobposting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
